### ISSUE TITLE
Doesn't work/sync across devices

### ISSUE THREAD

**Issue by jmalais** [aaron-artille/gumshoe#9]
If possible include the option to sync the data to other devices or have an option to connect to gmail and send out an email on a weekly basis.

**Comment by aaron-artille** [comment]
E-mail thing is definitely crossing the line, plus it would require additional permissions (i.e. permission to query remote servers) that I'm not comfortable having users agree to since I don't want people to make a habit of naivety in granting apps/extensions such potentially dangerous abilities.

As for syncing across devices, it's something that could be added once basic security is introduced. AFAIK credentials are just stored in plaintext currently, not something I want users sending to Google willy-nilly (it's also notably unsafe just running locally in its present state... maybe Chrome has built-in crypto encapsulating local storage for sites/extensions, but I'd be impressed).
